name: ci-release
on:
  push:
    tags:
      'v*'
  workflow_dispatch:
jobs:
  build_and_publish:
    strategy:
      matrix:
        platform: [x64-linux, arm64-linux, x64-windows]
        include:
          - platform: x64-linux
            os: ubuntu-26.04
            preset: ninja-gcc
            exe: raintrix
            archive: x64-linux-raintrix-${{ github.ref_name }}.tar.xz
          - platform: arm64-linux
            os: ubuntu-26.04-arm
            preset: ninja-gcc
            exe: raintrix
            archive: arm64-linux-raintrix-${{ github.ref_name }}.tar.xz
          - platform: x64-windows
            os: windows-latest
            preset: ninja-clang
            exe: raintrix.exe
            archive: x64-windows-raintrix-${{ github.ref_name }}.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: init
        run: cmake -P .github/init.cmake
      - name: configure
        run: cmake -S . --preset=${{ matrix.preset }} -B build
      - name: build release
        run: cmake --build build --config=Release -- -v
      - name: install
        run: |
            cmake --install build --config=Release --prefix=.
            tar -acf ${{ matrix.archive }} bin/${{ matrix.exe }}
      - name: release
        uses: softprops/action-gh-release@v3.0.1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: ${{ matrix.archive }}
          draft: true
          fail_on_unmatched_files: true
